server:
  port: 8766
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: dataaggr-server
  rabbitmq:
    host: 192.168.11.14
    port: 5672
    username: rabbitadmin
    password: 123456